# Generated by Django 6.0.6 on 2026-06-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='shared_song',
            new_name='attached_song',
        ),
        migrations.AddField(
            model_name='message',
            name='attached_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
